### ISSUE TITLE
Suggestion: Creativity and Experience

### ISSUE THREAD

**Issue by lol3003** [Trawis/T5B1#1]
Is it possible to add maximum Creativity and Experience, or just one of them?

For me, that's the most challenging part of the game right now.

**Comment by Trawis** [comment]
I'll look into that. I'm not familiar with those features that are new in the game.

**Comment by lol3003** [comment]
No problem, I tried to find anything myself, but I can't even find documentation for this game. And it's not like anyone else did something with this, yet, so you can't look at other mods.

It would be great, but it's not necessary.

**Comment by mys721tx** [comment]
`Employee.Creativity` and `Employee.CreativityKnown` could be useful. I will give them a try shortly.

**Comment by mys721tx** [comment]
`Employee.LeadSpecialization` is also useful for the experience.

**Comment by mys721tx** [comment]
`System.Reflection` is prohibited so there is no way to modify creativity. Populating the candidate pool is a possible alternative.
