### ISSUE TITLE
Bug with Beta 1.2

### ISSUE THREAD

**Issue by Nykolas94** [Trawis/T5B1#10]
Hello,
Since the beta 1.2 there is a bug and the mod doesn't work anymore. Could you update it ?
There is also a bug with the command max stat if you can do something with your mod.

Thank you :)

**Comment by Trawis** [comment]
Hi,
I'm on beta 1.2 and everything is working, please describe the problem a little more.

**Comment by Nykolas94** [comment]
Hi,
I took a screen of the error in the console if it can help you.
For information i have the mod "FloorMod" and "Expanse (Beta 1)", i don't know if this can interfere with you mod.
[https://zupimages.net/up/22/37/c0cs.png](url)

**Comment by Nykolas94** [comment]
Do you need another element ?

**Comment by Trawis** [comment]
You can disable floor mod, the trainer already has 100 floors enabled.
Do you use steam version?

**Comment by Nykolas94** [comment]
I removed the "floor mod" and the error was still there. So i unfollow your mod "Trainer" and i followed it again and the error is solved.
Everything is working fine. Thank you for your help :)
