### ISSUE TITLE
[FEATURE] Confirm dialog for max reputation/followers

### ISSUE THREAD

**Issue by Greymagic27** [Trawis/T5B1#29]
**Is your feature request related to a problem? Please describe.**
Currently it's very easy to misclick the max reputation or max followers buttons and then this is applied without any confirmation and cannot be undone

**Describe the solution you'd like**
Add a confirmation dialog to ensure this isn't done by mistake, or add a way to undo this

**Describe alternatives you've considered**

**Additional context**

**Comment by Trawis** [comment]
@Greymagic27 Max Followers option asks you for a product name so it cannot be misclicked the first time. I will add confirmation for max reputation.

**Comment by Trawis** [comment]
@Greymagic27 Added in d3f2ca5
