### ISSUE TITLE
Trainer causing the game to stutter

### ISSUE THREAD

**Issue by HackingDonkey** [Trawis/T5B1#4]
Hello,  I have discovered an issue with your mod causing significant frame drops (to 1 fps) while playing with it turned on.
https://www.youtube.com/watch?v=7g3goKkrZNs (Here is a fragment of my 'gaming experience' with your mod)
![image](https://user-images.githubusercontent.com/21294707/163578834-ad9ee78b-8c9e-4015-9d24-fc2c1c6424ba.png)
(these are my trainer settings)

If I turn your mod off, I will not have any issues with lag spikes, even if I have more employees.

(PC Specs: Ryzen 3700x, GTX1070Ti, 16gb ram and game is installed on a SSD)

**Comment by Trawis** [comment]
How many employees do you have? Could you test it by turning off each option to see which one is the most problematic. Also, can you send a savegame so I can reproduce this?

**Comment by Trawis** [comment]
Closing. No answer for almost a year.
